# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Open Graph Property

# Model Form Field configuration
form: $/unrebel/ucseo/models/opengraphproperty/fields.yaml

# Model Class name
modelClass: Unrebel\Ucseo\Models\OpenGraphProperty

# Default redirect location
defaultRedirect: unrebel/ucseo/opengraphproperties

# Create page
create:
    title: Create Open Graph Property
    redirect: unrebel/ucseo/opengraphproperties/update/:id
    redirectClose: unrebel/ucseo/opengraphproperties

# Update page
update:
    title: Edit Open Graph Property
    redirect: unrebel/ucseo/opengraphproperties
    redirectClose: unrebel/ucseo/opengraphproperties

# Preview page
preview:
    title: Preview Open Graph Property